name: deploy
on:
  workflow_dispatch:
    inputs:
      stage:
        description: "Please select a stage."
        required: true
        default: stg
        type: choice
        options:
          - stg
          - prd
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  aws-test:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::280107060642:role/yus-sakai-github-actions-test
          aws-region: ap-northeast-1
      - name: setup Node.js v18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - name: setup yarn
        run: npm i -g yarn
      - name: install cdk dependencies
        run: |
          yarn install --frozen-lockfile
      - name: cdk deploy
        run: |
          yarn deploy-${{ inputs.stage }}
