name: Deployment

on:
  workflow_dispatch: ~
  push: ~

jobs:
  deployment:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: staging
    needs: lint
    steps:
      - name: deploy
        run: echo 'deploy...'
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Enable Yarn v3
        run: corepack enable && corepack prepare yarn@3.6.0 --activate
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-18.16.0-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-18.16.0-
      - name: Confirm yarn
        run: yarn --version
  lint:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: lint
        run: echo 'lint...'
