name: Deployment

on:
  workflow_dispatch:
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: staging
    needs: lint
    steps:
      - name: deploy
        run: echo 'deploy...'
  lint:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: lint
        run: echo 'lint...'
