name: Deployment

on:
  workflow_dispatch: ~
  push: ~

env:
  NODE_VERSION: 18.16.0
  
jobs:
  deployment:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: staging
    needs: lint
    steps:
      - name: deploy
        run: echo 'deploy...'
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Enable Yarn v3
        run: corepack enable && corepack prepare yarn@3.6.0 --activate
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - name: confirm dir
        run: echo '${{ toJSON(steps.yarn-cache-dir-path.outputs) }}' && yarn config get cacheFolder
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ env.NODE_VERSION }}-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ env.NODE_VERSION }}-
      - name: Confirm yarn
        run: yarn --version
  lint:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: lint
        run: echo 'lint...'
